config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments, only: [:create, :destroy]
  end
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: { minimum: 5 }
	validates :content, presence: true
	validates :image, presence: true
	mount_uploader :image, PhotoUploader
	has_many :comments, dependent: :destroy

	# has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(comment_params)
		@comment.user = current_user
		@comment.save!
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.order("created_at DESC")
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to posts_path, notice: "文章建立成功"
		else
			render "new", alert: "文章建立失敗"
		end
	end

	def show
		@comment = Comment.new
		@comments = @post.comments.order("created_at DESC")
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to post_path, notice: "文章修改成功"
		else
			render "edit", alert: "文章修改失敗"
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path, alert: "文章已被刪除"
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :image)
	end

	def find_post
		@post = Post.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for [@post, @comment] do |f| %>
	<div class="form-group">
		<%= f.text_area :content, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit class: "btn btn-primary btn-sm" %>
	</div>
<% end %>

app/views/comments/_comment_show.html.erb
<% @comments.each do |comment| %>
	<div>
		<h6><%= comment.user.email.split("@").first %></h6>
		<p><%= simple_format comment.content %></p>
		<p class="text-muted">
			<em><%= comment.created_at %></em>
		</p>
		<% if user_signed_in? %>
			<%= link_to "Delete", post_comment_path(@post, comment), method: :delete, class: "float-right btn btn-danger btn-sm" %>
		<% end %>
	</div>
	<hr class="comment_hr">
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm sticky-top bg-dark mb-4">
  <div class="container">
    <%= link_to "Vita Forum", posts_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "New Post", new_post_path, class: "nav-link btn btn-outline-info" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline-info ml-4" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn btn-outline-info" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link btn btn-outline-info ml-4" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_message.html.erb
<% if flash[:notice] %>
  <div class="container mt-3">
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <strong><%= notice %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="container mt-3">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong><%= alert %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/message" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<section id="section_forum_form">
	<div class="container">
		<div class="row">
			<div class="col-10 offset-1">
				
				<%= form_for @post do |f| %>
	
					<% if @post.errors.any? %>
				    <h2>We have some errors here !</h2>
				    <ul>
				      <% @post.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				    </ul>
				  <% end %>

					<div class="form-group">
						<span class="text-danger">*</span>
						<%= f.label :title, "文章標題：" %>
						<%= f.text_field :title, class: "form-control" %>
					</div>

					<div class="form-group">
						<span class="text-danger">*</span>
						<%= f.label :content, "文章內容：" %>
						<%= f.text_area :content,rows: "18", class: "form-control" %>
					</div>

					<div class="form-group">
						<div class="custom-file">
						  <%= f.file_field :image,class: "custom-file-input" %>
						  <%= f.label :image, "Photo",class: "custom-file-label" %>
						</div>
					</div>

					<div class="form-group">
						<%= f.submit class: "btn btn-success btn-lg" %>
					</div>

				<% end %>

			</div>
		</div>
	</div>
</section>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<section id="section_forum_index">
	<div class="container">
		<div class="row">
			<div class="col-10 offset-1">
				
				<div class="forum">
					<% @posts.each do |post| %>
						<div class="row forum-item">
							<div class="col-3">
								<%= image_tag post.image.url, class: "img" %>
							</div>
							<div class="col-9">
								<h3 class="mb-4"><%= link_to post.title, post_path(post),class: "text-info" %></h3>
								<p>
									<%= truncate(post.content, length: 160) %>
									<%= link_to "繼續閱讀", post_path(post), class: "badge badge-info" %>
								</p>
							</div>
						</div>
						<hr>
					<% end %>
				</div>
				
			</div>
		</div>
	</div>
</section>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<section id="section_forum_show">
	<div class="container">
		<div class="row">
			<div class="col-10 offset-1">
				
				<% if user_signed_in?%>
					<div class="btn-group mb-2" role="group" aria-label="Basic example">
						<%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-warning" %>
						<%= link_to "Delete", post_path(@post),method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-warning" %>
					</div>
				<% end %>

				<h1 class="text-center mb-1"><%= @post.title %></h1>
				<p class="text-muted mb-2">
					Published at <%= time_ago_in_words(@post.created_at) %> ago -
					by <%= @post.user.email.split("@").first %>
				</p>
				<%= image_tag @post.image.url, class: "rounded mx-auto d-block img img-fluid" %>
				<div class="mt-3 text-size">
					<%= simple_format @post.content %>
				</div>

				<h5><%= @post.comments.count %> 則評語</h5>
				<%= render "comments/comment_show" %>
				<% if user_signed_in? %>
					<%= render "comments/comment_form" %>
				<% end %>

			</div>
		</div>
	</div>
</section>